package fate;
import java.util.*;

public final class Algoritmos {
  private Algoritmos(){}
  public static int[] mergeSort(){int[] a=ids(); mergeSort(a,0,a.length-1); return a;}
  private static int[] ids(){int[] a=new int[Datos.N];for(int i=0;i<a.length;i++)a[i]=i;return a;}
  private static void mergeSort(int[]a,int l,int r){if(l>=r)return;int m=(l+r)>>>1;mergeSort(a,l,m);mergeSort(a,m+1,r);int[]t=new int[r-l+1];int i=l,j=m+1,k=0;while(i<=m&&j<=r)t[k++]=Datos.PODER[a[i]]>=Datos.PODER[a[j]]?a[i++]:a[j++];while(i<=m)t[k++]=a[i++];while(j<=r)t[k++]=a[j++];System.arraycopy(t,0,a,l,t.length);}
  public static String mergeTrace(){StringBuilder s=new StringBuilder();s.append("Divide: dividir por mitades\nConquista: ordenar recursivamente\nCombinar: fusionar por poder descendente\n\n");for(int i:mergeSort())s.append(Datos.NOMBRE[i]).append(" -> ").append(Datos.PODER[i]).append("\n");return s.toString();}
  public static int[] greedy(int presupuesto,StringBuilder log){Integer[] a=new Integer[Datos.N];for(int i=0;i<Datos.N;i++)a[i]=i;Arrays.sort(a,(x,y)->Double.compare((double)Datos.PODER[y]/Datos.COSTO[y],(double)Datos.PODER[x]/Datos.COSTO[x]));int[]o=new int[Datos.N];int n=0,c=0;for(int i:a){double r=(double)Datos.PODER[i]/Datos.COSTO[i];log.append(String.format("%-18s ratio %.2f",Datos.NOMBRE[i],r));if(c+Datos.COSTO[i]<=presupuesto){o[n++]=i;c+=Datos.COSTO[i];log.append(" -> TOMAR\n");}else log.append(" -> DESCARTAR\n");}return Arrays.copyOf(o,n);}
  public static int[] mochila(int presupuesto,StringBuilder log){int[][]dp=new int[Datos.N+1][presupuesto+1];for(int i=1;i<=Datos.N;i++)for(int c=0;c<=presupuesto;c++){dp[i][c]=dp[i-1][c];if(Datos.COSTO[i-1]<=c)dp[i][c]=Math.max(dp[i][c],dp[i-1][c-Datos.COSTO[i-1]]+Datos.PODER[i-1]);}int[]tmp=new int[Datos.N];int n=0,c=presupuesto;for(int i=Datos.N;i>0;i--)if(dp[i][c]!=dp[i-1][c]){tmp[n++]=i-1;c-=Datos.COSTO[i-1];}log.append("Óptimo global: ").append(dp[Datos.N][presupuesto]).append(" poder\nMatriz DP: ").append(Datos.N+1).append(" x ").append(presupuesto+1).append("\n");return Arrays.copyOf(tmp,n);}
  public static int[] backtracking(int slots,int objetivo,StringBuilder log){int[]sol=new int[slots];Arrays.fill(sol,-1);boolean[]u=new boolean[Datos.N];if(bt(0,slots,objetivo,0,sol,u,log))return sol;return new int[0];}
  private static boolean bt(int p,int slots,int obj,int power,int[]sol,boolean[]u,StringBuilder log){if(p==slots){return power>=obj;}for(int i=0;i<Datos.N;i++){if(u[i])continue;boolean dup=false;for(int j=0;j<p;j++)if(Datos.CLASE[sol[j]].equals(Datos.CLASE[i]))dup=true;if(dup)continue;sol[p]=i;u[i]=true;log.append("  ".repeat(p)).append("Elegir ").append(Datos.NOMBRE[i]).append(" (poder ").append(Datos.PODER[i]).append(")\n");if(bt(p+1,slots,obj,power+Datos.PODER[i],sol,u,log))return true;u[i]=false;sol[p]=-1;log.append("  ".repeat(p)).append("↩ backtrack\n");}return false;}
  public static int[] bfs(int start,StringBuilder log){int n=Datos.N;int[]q=new int[n],order=new int[n];boolean[]v=new boolean[n];int h=0,t=0,k=0;q[t++]=start;v[start]=true;while(h<t){int u=q[h++];order[k++]=u;log.append("Visita: ").append(Datos.NOMBRE[u]).append("\n");for(int w:vecinos(u))if(!v[w]){v[w]=true;q[t++]=w;}}return Arrays.copyOf(order,k);}
  private static int[] vecinos(int u){int[]tmp=new int[Datos.N];int k=0;for(int v=0;v<Datos.N;v++)if(v!=u&&Math.abs(Datos.PODER[u]-Datos.PODER[v])<=120)tmp[k++]=v;return Arrays.copyOf(tmp,k);}
  public static int[] dijkstra(int start,StringBuilder log){int n=Datos.N;int[]d=new int[n],p=new int[n];boolean[]v=new boolean[n];Arrays.fill(d,9999);Arrays.fill(p,-1);d[start]=0;for(int it=0;it<n;it++){int u=-1;for(int i=0;i<n;i++)if(!v[i]&&(u<0||d[i]<d[u]))u=i;if(u<0||d[u]==9999)break;v[u]=true;for(int w:vecinos(u)){int nd=d[u]+1;if(nd<d[w]){d[w]=nd;p[w]=u;}}}log.append("Distancias desde ").append(Datos.NOMBRE[start]).append(":\n");for(int i=0;i<n;i++)log.append(Datos.NOMBRE[i]).append(" = ").append(d[i]==9999?"∞":d[i]).append("\n");return d;}
  public static String huffman(String text,StringBuilder log){int[]f=new int[256];for(char c:text.toCharArray())if(c<256)f[c]++;PriorityQueue<Node>pq=new PriorityQueue<>(Comparator.comparingInt(x->x.freq));for(int i=0;i<256;i++)if(f[i]>0)pq.add(new Node((char)i,f[i],null,null));while(pq.size()>1){Node a=pq.poll(),b=pq.poll();pq.add(new Node('\0',a.freq+b.freq,a,b));}Map<Character,String>codes=new HashMap<>();if(!pq.isEmpty())code(pq.peek(),"",codes);StringBuilder bits=new StringBuilder();for(char c:text.toCharArray())bits.append(codes.get(c));log.append("Frecuencias y códigos Huffman:\n");for(var e:codes.entrySet())log.append(printChar(e.getKey())).append(" = ").append(e.getValue()).append("\n");log.append("\nOriginal: ").append(text.length()*8).append(" bits\nComprimido: ").append(bits.length()).append(" bits\nAhorro: ").append(String.format("%.1f",100.0*(1.0-(double)bits.length()/(text.length()*8)))).append("%\n");return bits.toString();}
  private static void code(Node n,String p,Map<Character,String>m){if(n.left==null&&n.right==null){m.put(n.ch,p.isEmpty()?"0":p);return;}code(n.left,p+"0",m);code(n.right,p+"1",m);}
  private static String printChar(char c){return c==' ' ? "[espacio]" : ""+c;}
  private record Node(char ch,int freq,Node left,Node right){}
  public static int[] combate(int a,int b,long seed,StringBuilder log){int va=Datos.VIDA[a],vb=Datos.VIDA[b];Random r=new Random(seed);int round=1;while(va>0&&vb>0&&round<=20){int da=Math.max(20,Datos.PODER[a]/5+r.nextInt(70)-25);int db=Math.max(20,Datos.PODER[b]/5+r.nextInt(70)-25);vb-=da;log.append("Ronda ").append(round).append(": ").append(Datos.NOMBRE[a]).append(" golpea por ").append(da).append(" -> vida rival ").append(Math.max(vb,0)).append("\n");if(vb<=0)break;va-=db;log.append("          ").append(Datos.NOMBRE[b]).append(" responde por ").append(db).append(" -> vida rival ").append(Math.max(va,0)).append("\n");round++;}return new int[]{Math.max(va,0),Math.max(vb,0),va>=vb?a:b};}
  public static int suma(int[]ids,int[]v){int s=0;for(int i:ids)s+=v[i];return s;}
  public static String[] names(int[]ids){String[]s=new String[ids.length];for(int i=0;i<ids.length;i++)s[i]=ids[i]>=0?Datos.NOMBRE[ids[i]]:"-";return s;}
}
