package fate;
import javax.swing.*;import java.awt.*;import java.util.*;
public class DesktopApp{
 static final Color BG=new Color(9,8,17),CARD=new Color(25,20,37),TXT=new Color(245,240,250),ACC=new Color(186,88,255);
 public static void mostrar(){SwingUtilities.invokeLater(()->{JFrame f=new JFrame("FATE/STAY NIGHT — ALGORITHM ARENA 3.0");f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);f.setSize(1280,800);f.setLocationRelativeTo(null);JTabbedPane t=new JTabbedPane();t.addTab("Waifus",waifus());t.addTab("Combate",combat());t.addTab("Divide & Conquista",algo("MERGE SORT",1));t.addTab("Voraz",algo("GREEDY",2));t.addTab("Dinámica",algo("MOCHILA 0/1",3));t.addTab("Backtracking",algo("FORMACIÓN",4));t.addTab("Grafos",algo("BFS + DIJKSTRA",5));t.addTab("Huffman",algo("COMPRESIÓN",6));JPanel root=new JPanel(new BorderLayout());root.setBackground(BG);JLabel h=new JLabel("FATE/STAY NIGHT  •  ALGORITHM ARENA 3.0",SwingConstants.CENTER);h.setForeground(TXT);h.setFont(new Font("SansSerif",Font.BOLD,26));h.setBorder(BorderFactory.createEmptyBorder(16,10,16,10));root.add(h,BorderLayout.NORTH);root.add(t,BorderLayout.CENTER);JButton web=new JButton("ABRIR PANEL WEB");web.addActionListener(e->{try{WebServer.iniciar(8080);Desktop.getDesktop().browse(new java.net.URI("http://localhost:8080"));}catch(Exception x){JOptionPane.showMessageDialog(f,x.toString());}});root.add(web,BorderLayout.SOUTH);f.setContentPane(root);f.setVisible(true);});}
 static JPanel waifus(){JPanel p=base();JTextArea a=area();for(int i=0;i<Datos.N;i++)a.append(String.format("%-16s | %-11s | Poder %4d | Vida %4d | Costo %2d | %s\n    %s\n\n",Datos.NOMBRE[i],Datos.CLASE[i],Datos.PODER[i],Datos.VIDA[i],Datos.COSTO[i],Datos.NOBLE[i],Datos.HISTORIA[i]));p.add(new JScrollPane(a));return p;}
 static JPanel combat(){JPanel p=base();JComboBox<String>a=new JComboBox<>(Datos.NOMBRE),b=new JComboBox<>(Datos.NOMBRE);JButton go=new JButton("INICIAR COMBATE");JTextArea out=area();JPanel top=new JPanel();top.setOpaque(false);top.add(new JLabel("Servant A"));top.add(a);top.add(new JLabel("VS"));top.add(b);top.add(go);p.add(top,BorderLayout.NORTH);p.add(new JScrollPane(out),BorderLayout.CENTER);go.addActionListener(e->{int x=a.getSelectedIndex(),y=b.getSelectedIndex();if(x==y){out.setText("Elegí dos Servants diferentes.");return;}StringBuilder s=new StringBuilder();int[]r=Algoritmos.combate(x,y,System.nanoTime(),s);out.setText("GANADORA: "+Datos.NOMBRE[r[2]]+"\nVida final A: "+r[0]+" | Vida final B: "+r[1]+"\n\n"+s);});return p;}
 static JPanel algo(String title,int n){JPanel p=base();JButton go=new JButton("EJECUTAR");JTextArea out=area();JPanel top=new JPanel();top.setOpaque(false);top.add(new JLabel(title));top.add(go);p.add(top,BorderLayout.NORTH);p.add(new JScrollPane(out),BorderLayout.CENTER);go.addActionListener(e->{StringBuilder s=new StringBuilder();if(n==1)out.setText(Algoritmos.mergeTrace());if(n==2){int[]r=Algoritmos.greedy(25,s);out.setText("Presupuesto 25\n\n"+s+"\nEquipo: "+Arrays.toString(Algoritmos.names(r))+"\nPoder: "+Algoritmos.suma(r,Datos.PODER));}if(n==3){int[]r=Algoritmos.mochila(25,s);out.setText("Presupuesto 25\n\n"+s+"\nEquipo óptimo: "+Arrays.toString(Algoritmos.names(r))+"\nPoder: "+Algoritmos.suma(r,Datos.PODER));}if(n==4){int[]r=Algoritmos.backtracking(4,3300,s);out.setText("Objetivo 3300 / 4 clases distintas\n\n"+s+"\nResultado: "+Arrays.toString(Algoritmos.names(r)));}if(n==5){Algoritmos.bfs(0,s);s.append("\nDijkstra:\n");Algoritmos.dijkstra(0,s);out.setText("Grafo: conectamos Servants con diferencia de poder <= 120.\n\n"+s);}if(n==6){String text="La historia de Saber representa el ideal de un rey y su lucha por cambiar su destino.";String bits=Algoritmos.huffman(text,s);out.setText(s+"\nBits: "+bits);}});return p;}
 static JPanel base(){JPanel p=new JPanel(new BorderLayout(10,10));p.setBorder(BorderFactory.createEmptyBorder(12,12,12,12));p.setBackground(BG);return p;}static JTextArea area(){JTextArea a=new JTextArea();a.setEditable(false);a.setForeground(TXT);a.setBackground(CARD);a.setFont(new Font(Font.MONOSPACED,Font.PLAIN,14));a.setLineWrap(true);a.setWrapStyleWord(true);return a;}
}
