package fate;
import com.sun.net.httpserver.*;import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;import java.nio.file.*;import java.util.*;
public class WebServer{
 static HttpServer server; static Path BASE=Path.of("src/main/resources/web").toAbsolutePath().normalize();
 public static void main(String[]a)throws Exception{iniciar(8080);System.out.println("Web: http://localhost:8080");}
 public static void iniciar(int port)throws Exception{if(server!=null)return;server=HttpServer.create(new InetSocketAddress(port),0);server.createContext("/api/personajes",e->respond(e,jsonCharacters(),"application/json"));server.createContext("/api/algoritmos",WebServer::algorithms);server.createContext("/api/combate",WebServer::combat);server.createContext("/",WebServer::staticFile);server.setExecutor(null);server.start();}
 static void algorithms(HttpExchange e)throws IOException{respond(e,"{\"mergeSort\":\"Divide y conquista\",\"voraz\":\"Selección por ratio poder/costo\",\"dinamica\":\"Mochila 0/1\",\"backtracking\":\"Equipo bajo restricciones\",\"grafos\":\"BFS + Dijkstra sobre red de afinidades\",\"huffman\":\"Codificación Huffman del historial\"}","application/json");}
 static void combat(HttpExchange e)throws IOException{if(!"POST".equalsIgnoreCase(e.getRequestMethod())){respond(e,"{\"error\":\"POST requerido\"}","application/json");return;}String body=new String(e.getRequestBody().readAllBytes(),StandardCharsets.UTF_8);Map<String,String>m=parse(body);try{int a=Integer.parseInt(m.getOrDefault("a","0")),b=Integer.parseInt(m.getOrDefault("b","1"));if(a==b)throw new IllegalArgumentException("Seleccioná dos Servants diferentes.");StringBuilder log=new StringBuilder();int[]r=Algoritmos.combate(a,b,System.nanoTime(),log);respond(e,"{\"a\":\""+q(Datos.NOMBRE[a])+"\",\"b\":\""+q(Datos.NOMBRE[b])+"\",\"winner\":\""+q(Datos.NOMBRE[r[2]])+"\",\"vidaA\":"+r[0]+",\"vidaB\":"+r[1]+",\"log\":\""+q(log.toString())+"\"}","application/json");}catch(Exception ex){respond(e,"{\"error\":\""+q(ex.getMessage())+"\"}","application/json");}}
 static Map<String,String> parse(String s){Map<String,String>m=new HashMap<>();for(String p:s.replace("{","").replace("}","").replace("\"","").split(",")){String[]x=p.split(":");if(x.length==2)m.put(x[0].trim(),x[1].trim());}return m;}
 static String jsonCharacters(){StringBuilder s=new StringBuilder("[");for(int i=0;i<Datos.N;i++){if(i>0)s.append(',');s.append("{\"id\":").append(i).append(",\"nombre\":\"").append(q(Datos.NOMBRE[i])).append("\",\"identidad\":\"").append(q(Datos.IDENTIDAD[i])).append("\",\"clase\":\"").append(q(Datos.CLASE[i])).append("\",\"poder\":").append(Datos.PODER[i]).append(",\"costo\":").append(Datos.COSTO[i]).append(",\"mana\":").append(Datos.MANA[i]).append(",\"vida\":").append(Datos.VIDA[i]).append(",\"master\":\"").append(q(Datos.MASTER[i])).append("\",\"noble\":\"").append(q(Datos.NOBLE[i])).append("\",\"historia\":\"").append(q(Datos.HISTORIA[i])).append("\",\"imagen\":\"").append(q(Datos.IMAGEN[i])).append("\",\"color\":\"").append(Datos.COLOR[i]).append("\"}");}return s.append(']').toString();}
 static String q(String s){if(s==null)return "";return s.replace("\\","\\\\").replace("\"","\\\"").replace("\r","").replace("\n","\\n");}
 static void respond(HttpExchange e,String body,String type)throws IOException{byte[]b=body.getBytes(StandardCharsets.UTF_8);e.getResponseHeaders().set("Access-Control-Allow-Origin","*");e.getResponseHeaders().set("Content-Type",type+"; charset=UTF-8");e.sendResponseHeaders(200,b.length);try(OutputStream o=e.getResponseBody()){o.write(b);}}
 static void staticFile(HttpExchange e)throws IOException{String p=e.getRequestURI().getPath();if(p.equals("/"))p="/index.html";Path f=BASE.resolve(p.substring(1)).normalize();if(!f.startsWith(BASE)||!Files.exists(f)||Files.isDirectory(f)){e.sendResponseHeaders(404,-1);return;}String ct=Files.probeContentType(f);if(ct==null){if(p.endsWith(".js"))ct="application/javascript";else if(p.endsWith(".css"))ct="text/css";else if(p.endsWith(".mp4"))ct="video/mp4";else ct="application/octet-stream";}byte[]b=Files.readAllBytes(f);e.getResponseHeaders().set("Content-Type",ct);e.sendResponseHeaders(200,b.length);try(OutputStream o=e.getResponseBody()){o.write(b);}}
}
